"""The Construction Forecast panel: its static HTML region and its data file.

Called by sitegen.py. Input is tools/data/construction.json, written by
tools/extract_construction.py from the forecasting engine's committed results.

    construction_js()      -> assets/lab/construction-data.js (the scenario model the page computes with)
    construction_region()  -> the <!-- gen:construction --> region of lab.html

Every number here is read from that file. The static region carries the
controls, the "How it works" tables, a no-script fallback of every preset, and
the real macro forecast as inline SVG, so the page reads in full without
JavaScript. assets/lab/construction.js draws the scenario charts.

The region is checked against the site's copy rules before it is returned, so a
semicolon or an em dash in a source title stops the build instead of shipping.
"""

from __future__ import annotations

import json
import re
from html import escape, unescape
from pathlib import Path

DATA = Path(__file__).resolve().parent / "data" / "construction.json"
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
BANNED = [("semicolon", ";"), ("em dash", "—"), ("retired date", r"October\s+2026"),
          ("retired figure", r"\b251\b|\b2041\b")]
NUMBER_WORDS = {4: "Four", 5: "Five", 6: "Six", 7: "Seven", 8: "Eight"}
WHY_SENTENCE = ("Most sliders move the 12-month plan only a little because most of the year's revenue is backlog "
                "that is already signed, and a rate change reaches revenue only through new bookings months later. "
                "Funding timing moves revenue the most because a delayed bill cuts public bookings right away.")


def load() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def construction_js() -> str:
    d = load()
    keep = {"model": d["contractor"]["model"], "company": d["contractor"]["company"],
            "provenance": {k: d["provenance"][k] for k in ("commit", "commit_date")},
            "snapshot": d["sources"]["snapshot"],
            "samples": [{k: s[k] for k in ("key", "label", "series_id", "title", "dates", "values", "settings")}
                        for s in d["samples"]["samples"]]}
    return ("// Generated by tools/sitegen.py from tools/data/construction.json (tools/extract_construction.py).\n"
            "// The scenario model's inputs, from the forecasting engine's committed results. Do not edit.\n"
            "window.CONSTRUCTION_DATA = " + json.dumps(keep, separators=(",", ":"), ensure_ascii=False) + ";\n")


# ------------------------------------------------------------------ formatting -----
def money(k: float, digits: int = 1) -> str:
    """USD thousands in, '$260.0M' out. Minus sign, never an em dash, never on zero."""
    v = k / 1000
    text = f"{abs(v):,.{digits}f}"
    return ("−" if v < 0 and float(text.replace(",", "")) != 0 else "") + f"${text}M"


def signed(k: float) -> str:
    """The same rule as the page's signedMoney: under $50K of change reads as zero."""
    if abs(k) < 50:
        return "$0.0M"
    return ("+" if k > 0 else "") + money(k)


def month(ym: str) -> str:
    year, m = ym[:4], int(ym[5:7])
    return f"{MONTHS[m - 1]} {year}"


def pct(x: float, digits: int = 2) -> str:
    return f"{100 * x:.{digits}f}%"


def e(text) -> str:
    return escape(str(text), quote=True)


# --------------------------------------------------------------- macro chart -----
def macro_chart(macro: dict) -> str:
    """Recent actuals and the published forecast with its P10 to P90 range of past misses."""
    actual = macro["recent_actuals"]
    fc = macro["published"]["forecast"]
    W, H, L, R, T, B = 640, 300, 64, 16, 16, 40
    values = [a["value"] for a in actual] + [f["p10"] for f in fc] + [f["p90"] for f in fc]
    step = 10000
    y0, y1 = (min(values) // step) * step, (max(values) // step + 1) * step
    # The forecast starts after the publication-lag month, which is left blank
    # rather than drawn as if it were known.
    index = lambda ym: int(ym[:4]) * 12 + int(ym[5:7])  # noqa: E731
    first_fc = len(actual) - 1 + index(fc[0]["date"]) - index(actual[-1]["date"])
    n = first_fc + len(fc)
    x = lambda i: L + i / (n - 1) * (W - L - R)  # noqa: E731
    y = lambda v: T + (y1 - v) / (y1 - y0) * (H - T - B)  # noqa: E731
    out = [f'<svg class="chart" viewBox="0 0 {W} {H}" width="{W}" height="{H}" role="img" aria-labelledby="cfm-t cfm-d">',
           '<title id="cfm-t">U.S. private nonresidential construction spending, actual and forecast</title>',
           f'<desc id="cfm-d">Monthly spending, not seasonally adjusted, in millions of dollars. Actual data from '
           f'{month(actual[0]["date"][:7])} to {month(actual[-1]["date"][:7])}, ending at {actual[-1]["value"]:,.0f}. '
           f'Published forecast from {month(fc[0]["date"][:7])} to {month(fc[-1]["date"][:7])}: '
           f'{fc[0]["point"]:,.0f} in the first month and {fc[-1]["point"]:,.0f} in the last, with a P10 to P90 range of past '
           f'misses from {fc[-1]["p10"]:,.0f} to {fc[-1]["p90"]:,.0f} in the last month. The numbers are in the table below.</desc>']
    v = y0
    while v <= y1:
        out.append(f'<line class="ch-grid" x1="{L}" x2="{W - R}" y1="{y(v):.1f}" y2="{y(v):.1f}"/>'
                   f'<text class="ch-tick" x="{L - 8}" y="{y(v) + 4:.1f}" text-anchor="end">${v / 1000:,.0f}B</text>')
        v += step
    labels = [(i, a["date"][:7]) for i, a in enumerate(actual)] + [(first_fc + j, f["date"][:7]) for j, f in enumerate(fc)]
    for i, ym in labels:
        if ym[5:7] == "01":
            out.append(f'<text class="ch-tick" x="{x(i):.1f}" y="{H - B + 20}" text-anchor="middle">{ym[:4]}</text>')
    band = ([f"{x(first_fc + j):.1f} {y(f['p90']):.1f}" for j, f in enumerate(fc)]
            + [f"{x(first_fc + j):.1f} {y(f['p10']):.1f}" for j, f in reversed(list(enumerate(fc)))])
    out.append(f'<path class="cf-band" d="M{" L".join(band)} Z"/>')
    out.append('<path class="ch-line cf-actual" d="M' + " L".join(f"{x(i):.1f} {y(a['value']):.1f}"
                                                                for i, a in enumerate(actual)) + '"/>')
    out.append('<path class="ch-line cf-scen" d="M' + " L".join(f"{x(first_fc + j):.1f} {y(f['point']):.1f}"
                                                              for j, f in enumerate(fc)) + '"/>')
    out.append("</svg>")
    return "".join(out)


# -------------------------------------------------------------------- tables -----
def backtest_table(macro: dict) -> str:
    variants = macro["variants"]
    head = "".join(f'<th scope="col">Avg MAPE, lag {v["publication_lag_months"]}</th>'
                   f'<th scope="col">12 months ahead, lag {v["publication_lag_months"]}</th>' for v in variants)
    rows = []
    for i, row in enumerate(variants[0]["table"]):
        cells = ""
        for v in variants:
            r = v["table"][i]
            mark = ' class="num cf-win"' if r["key"] == v["winner"] else ' class="num"'
            cells += f'<td{mark}>{r["mean_mape"]:.2f}%</td><td class="num">{r["h12_mape"]:.2f}%</td>'
        rows.append(f'<tr><th scope="row">{e(row["name"])}</th>{cells}</tr>')
    return ('<div class="table-scroll"><table class="mini cf-table"><caption class="sr-only">Backtest error by model</caption>'
            f'<thead><tr><th scope="col">Model</th>{head}</tr></thead><tbody>{"".join(rows)}</tbody></table></div>')


def coverage_table(macro: dict) -> str:
    variants = macro["variants"]
    head = "".join(f'<th scope="col">Inside the band, lag {v["publication_lag_months"]}</th>' for v in variants)
    rows = []
    for i in range(len(variants[0]["coverage"]["by_horizon"])):
        cells = "".join(f'<td class="num">{pct(v["coverage"]["by_horizon"][i]["coverage"], 0)} '
                        f'({v["coverage"]["by_horizon"][i]["covered"]} of {v["coverage"]["by_horizon"][i]["test_folds"]})</td>'
                        for v in variants)
        rows.append(f'<tr><th scope="row">{i + 1}</th>{cells}</tr>')
    return ('<div class="table-scroll"><table class="mini cf-table"><caption class="sr-only">Out of sample coverage of the '
            f'P10 to P90 band</caption><thead><tr><th scope="col">Months ahead</th>{head}</tr></thead>'
            f'<tbody>{"".join(rows)}</tbody></table></div>')


def forecast_table(macro: dict) -> str:
    rows = "".join(f'<tr><th scope="row">{month(f["date"][:7])}</th><td class="num">{f["p10"]:,.0f}</td>'
                   f'<td class="num">{f["point"]:,.0f}</td><td class="num">{f["p90"]:,.0f}</td></tr>'
                   for f in macro["published"]["forecast"])
    return ('<div class="table-scroll"><table class="mini cf-table"><thead><tr><th scope="col">Month</th>'
            '<th scope="col">P10</th><th scope="col">Forecast</th><th scope="col">P90</th></tr></thead>'
            f'<tbody>{rows}</tbody></table></div>')


def sources_table(src: dict) -> str:
    rows = "".join(f'<tr><th scope="row"><a href="{e(s["url"])}">{e(s["id"])}</a></th><td>{e(s["title"])}</td>'
                   f'<td>{e(s["used_as"])}</td><td class="num">{s["first"][:7]} to {s["last"][:7]}</td>'
                   f'<td class="num">{s["pulled"]}</td></tr>' for s in src["fred"])
    return ('<div class="table-scroll"><table class="mini cf-table"><caption class="sr-only">FRED series used</caption>'
            '<thead><tr><th scope="col">Series ID</th><th scope="col">Title</th><th scope="col">Used as</th>'
            f'<th scope="col">Data</th><th scope="col">Pulled</th></tr></thead><tbody>{rows}</tbody></table></div>')


OPS = {">": "above", ">=": "at or above", "<": "below", "<=": "at or below"}
UNITS = {"PRCP": " in of precipitation", "TMAX": "°F max temperature", "TMIN": "°F min temperature",
         "SNWD": " in of snow on the ground", "WSF2": " mph fastest 2-minute wind"}


def rule_text(element: str, op: str, threshold) -> str:
    return f"{OPS[op].capitalize()} {threshold:g}{UNITS[element]}"


def weather_table(src: dict) -> str:
    rows = []
    for rule in src["weather_rules"]:
        rows.append(f'<tr><th scope="row">{rule_text(rule["element"], rule["op"], rule["threshold"])}</th>'
                    f'<td><a href="{e(rule["url"])}">{e(rule["source"])}</a>: “{e(rule["quote"])}”</td></tr>')
    return ('<div class="table-scroll"><table class="mini cf-table"><caption class="sr-only">Adverse workday rules</caption>'
            '<thead><tr><th scope="col">A weekday is flagged when</th><th scope="col">Source</th></tr></thead>'
            f'<tbody>{"".join(rows)}</tbody></table></div>')


def factor_table(tiers: dict, labels: dict) -> str:
    rows = "".join(
        f'<tr><th scope="row">{rule_text(t["element"], t[level]["op"], t[level]["threshold"])}</th>'
        f'<td class="num">{pct(t[level]["factor"], 0)}</td><td>{e(labels[f"{key}_{level}"])}</td></tr>'
        for key, t in tiers.items() for level in ("light", "severe"))
    return ('<div class="table-scroll"><table class="mini cf-table"><caption class="sr-only">Productivity on a flagged day'
            '</caption><thead><tr><th scope="col">Condition</th><th scope="col">Share of a normal day done</th>'
            f'<th scope="col">Basis</th></tr></thead><tbody>{rows}</tbody></table></div>')


def preset_table(contractor: dict) -> str:
    labels = {p["key"]: p["label"] for p in contractor["model"]["presets"]}
    rows = []
    for key, r in contractor["reference"].items():
        t, c = r["views"]["12"], r["change_from_base"]["12"]
        mc = r["monte_carlo"]["views"]["12"]["revenue"]
        rows.append(f'<tr><th scope="row">{e(labels[key])}</th><td class="num">{money(t["revenue"])}</td>'
                    f'<td class="num">{money(t["gross_profit"])}</td><td class="num">{pct(t["gross_margin"])}</td>'
                    f'<td class="num">{signed(c["revenue"])}</td><td class="num">{signed(c["gross_profit"])}</td>'
                    f'<td class="num">{money(mc["p10"])} to {money(mc["p90"])}</td></tr>')
    return ('<div class="table-scroll"><table class="mini cf-table"><caption>Every preset over the 12-month plan, '
            'computed in Python</caption><thead><tr><th scope="col">Scenario</th><th scope="col">Revenue</th>'
            '<th scope="col">Gross profit</th><th scope="col">Gross margin</th><th scope="col">Change in revenue</th>'
            '<th scope="col">Change in gross profit</th><th scope="col">Spread of revenue outcomes</th></tr></thead>'
            f'<tbody>{"".join(rows)}</tbody></table></div>')


def backlog_table(model: dict) -> str:
    rows = "".join(f'<tr><th scope="row">{e(p["name"])}</th><td>{e(p["sector"]).capitalize()}</td>'
                   f'<td>{"Fixed price" if p["contract"] == "fixed" else "Escalation clause"}</td>'
                   f'<td class="num">{money(p["value"])}</td><td class="num">{pct(p["complete"], 0)}</td>'
                   f'<td class="num">{pct(p["margin"], 1)}</td></tr>' for p in model["backlog"]["projects"])
    return ('<div class="table-scroll"><table class="mini cf-table"><caption class="sr-only">Synthetic backlog</caption>'
            '<thead><tr><th scope="col">Project (synthetic)</th><th scope="col">Sector</th><th scope="col">Contract</th>'
            '<th scope="col">Value</th><th scope="col">Complete</th><th scope="col">Margin</th></tr></thead>'
            f'<tbody>{rows}</tbody></table></div>')


def episodes_list(model: dict) -> str:
    items = []
    for i, ep in enumerate(model["materials"]["episodes"]):
        metals = ", ".join(f"{k} {100 * v:+.1f}%" for k, v in ep["metals_log_change"].items())
        actions = (" Federal Register actions in the window: " + ", ".join(e(a) for a in ep["actions"]) + "."
                   if ep["actions"] else "")
        items.append(f'<li><strong>{e(ep["label"])}{" (default)" if i == 0 else ""}.</strong> {month(ep["from"])} to '
                     f'{month(ep["to"])}. Log change {metals}. Through the pass-through coefficients that is '
                     f'{100 * ep["ppi_effect"]:.2f}% on the construction input PPI. {e(ep["basis"])}{actions}</li>')
    return "<ul>" + "".join(items) + "</ul>"


# -------------------------------------------------------------------- region -----
def slider(id_: str, label: str, note: str = "") -> str:
    note_html = f'<p class="field-note">{note}</p>' if note else ""
    return (f'<div class="field"><label for="{id_}">{label}</label><div class="slider"><input type="range" id="{id_}">'
            f'<output for="{id_}" id="{id_}-out" class="cf-out" aria-live="off"></output></div>{note_html}</div>')


def defaults_sentence(d: dict) -> str:
    """One plain sentence on the difference that stays on purpose, built from the data."""
    main = next(x for x in d["samples"]["samples"] if x.get("settings"))
    general = next(x for x in d["samples"]["samples"] if not x.get("settings"))["result"]
    first, lag = main["settings"]["first_origin"], main["settings"]["publication_lag"]
    return (f"Your own files and the other samples are tested from the last {general['origins']} months with no "
            f"publication lag, because the page cannot know when your data is published, while the "
            f"{e(main['label'].lower())} sample uses the main forecast's settings, origins from "
            f"{MONTHS[first[1] - 1]} {first[0]} and data known {lag} month late, so both tabs show the same winner "
            f"and errors.")


def own_data_panel(d: dict) -> str:
    """The second tab. Its engine and parser are in assets/lab/autocast.js."""
    samples = d["samples"]
    return f'''        <div class="cf ac" id="ac" role="tabpanel" aria-labelledby="cf-tab-own" hidden>
          <p class="cf-label">Bring a monthly or quarterly series as a CSV with a date column and one value column. It is read and forecast entirely in this browser tab. Nothing is uploaded, sent or stored, and closing the tab discards it.</p>
          <div class="ac-input">
            <div class="ac-drop" id="ac-drop">
              <input type="file" id="ac-file" class="ac-file" accept=".csv,.txt,text/csv" aria-describedby="ac-formats">
              <label class="btn primary" for="ac-file">Choose a CSV file</label>
              <p class="small" id="ac-formats">Or drop it here. Dates like 2024-01, 01/2024, Jan 2024, 2024Q1 or 3/15/2024 (month first). Values may carry $ signs or quotes, and commas are read as thousands separators.</p>
            </div>
            <div class="presets" role="group" aria-labelledby="ac-samples-l">
              <span id="ac-samples-l" class="presets-label">Or try a sample: FRED data from this panel's snapshot, the last {e(samples["months"])} months</span>
              <div class="preset-row" id="ac-samples"></div>
            </div>
          </div>
          <p class="ac-status" id="ac-status" role="status" aria-live="polite"></p>
          <p class="ac-status ac-error" id="ac-error" role="alert" hidden></p>
          <div id="ac-results" hidden>
            <dl class="qf-stats cf-stats cf-stats-small">
              <div><dt>Frequency</dt><dd id="ac-freq"></dd></div>
              <div><dt>Points used</dt><dd class="num" id="ac-points"></dd></div>
              <div><dt>Seasonality</dt><dd id="ac-seasonal"></dd></div>
              <div><dt>Winner by backtest</dt><dd id="ac-winner"></dd></div>
              <div><dt>Backtest</dt><dd id="ac-origins"></dd></div>
            </dl>
            <figure class="chart-wrap">
              <svg class="chart" id="ac-chart" viewBox="0 0 640 280" width="640" height="280" role="img" aria-labelledby="ac-chart-t ac-chart-d"><title id="ac-chart-t">Your series and the winning model's forecast</title><desc id="ac-chart-d"></desc></svg>
              <figcaption><span class="key cf-actual">Your data</span><span class="key cf-scen">Forecast</span><span class="key cf-band-key">P10 to P90 range of past misses</span></figcaption>
            </figure>
            <div class="table-scroll"><table class="mini cf-table" id="ac-table"><caption>Backtest error by model, averaged over every horizon</caption><thead><tr><th scope="col">Model</th><th scope="col">Avg MAPE</th><th scope="col">Avg MAE</th><th scope="col">Tests per horizon</th></tr></thead><tbody></tbody></table></div>
            <p class="small" id="ac-mape-note"></p>
            <details><summary>Show the forecast numbers</summary><div class="table-scroll"><table class="mini cf-table" id="ac-forecast"><thead><tr><th scope="col">Period</th><th scope="col">P10</th><th scope="col">Forecast</th><th scope="col">P90</th></tr></thead><tbody></tbody></table></div></details>
            <p><button class="btn" type="button" id="ac-download">Download the forecast as CSV</button> <span class="small">Built in your browser from the numbers above.</span></p>
            <p class="small">How the winner is picked: seasonal naive, a linear trend with seasonality, and damped Holt-Winters are each tested by forecasting from every recent period in turn and comparing with what came next. The lowest average error wins, with ties going to the simpler model. The band is the range of that model's own past misses, not a probability. This is the forecasting engine's Python, ported to JavaScript, and the site's checks confirm the two agree on the samples.</p>
            <p class="small" id="ac-defaults">{defaults_sentence(d)}</p>
          </div>
          <noscript><p>This tab needs JavaScript. Your file would never leave your browser either way.</p></noscript>
        </div>'''



def construction_region() -> str:
    d = load()
    src, macro, con = d["sources"], d["macro"], d["contractor"]
    model, prov = con["model"], d["provenance"]
    lagged = next(v for v in macro["variants"] if v["publication_lag_months"] == macro["published"]["publication_lag_months"])
    winner = next(r for r in lagged["table"] if r["key"] == lagged["winner"])
    naive = next(r for r in lagged["table"] if r["key"] == "seasonal_naive")
    drivers = next(r for r in lagged["table"] if r["key"] == "drivers")
    rates = model["rates"]
    hist = rates["history"]
    lo_h, hi_h = min(h["growth_per_100bp"] for h in hist), max(h["growth_per_100bp"] for h in hist)
    wb = d["workbook"]
    verify_why(con)
    html = f'''<!-- gen:construction -->
        <div class="cf-tabs" id="cf-tabs" role="tablist" aria-label="Construction Forecast tools" hidden>
          <button type="button" role="tab" id="cf-tab-scen" aria-selected="true" aria-controls="cf">Contractor scenarios</button>
          <button type="button" role="tab" id="cf-tab-own" aria-selected="false" aria-controls="ac" tabindex="-1">Forecast your own data</button>
        </div>
        <div class="cf" id="cf" role="tabpanel" aria-labelledby="cf-tab-scen">
          <p class="cf-label"><span class="pill cf-real">Real forecast</span> U.S. private nonresidential construction spending ({e(macro["target"]["id"])}), forecast with {e(winner["name"])}. <span class="pill cf-fict">Fictional company</span> {e(con["company"])}: every company figure is synthetic and not modeled on any real company.</p>
          <div class="presets" role="group" aria-labelledby="cf-presets-l">
            <span id="cf-presets-l" class="presets-label">Scenarios</span>
            <div class="preset-row" id="cf-presets"></div>
          </div>
          <div class="mosca-controls cf-controls">
            {slider("cf-weather", "Weather")}
            <div class="field"><label for="cf-tariff">Tariffs on metals</label><div class="slider"><input type="range" id="cf-tariff"><output for="cf-tariff" id="cf-tariff-out" class="cf-out" aria-live="off"></output></div>
              <label class="cf-sub" for="cf-episode">Size the tariff on</label><select id="cf-episode"></select></div>
            {slider("cf-rates", "Interest rates")}
            {slider("cf-funding", "Federal surface transportation bill")}
            {slider("cf-diesel", "Diesel")}
          </div>
          <div class="cf-toggles">
            <fieldset class="cf-seg"><legend>Show</legend>
              <label><input type="radio" name="cf-view" value="{model["main_months"]}" checked> {model["main_months"]}-month plan</label>
              <label><input type="radio" name="cf-view" value="{len(model["months"])}"> {len(model["months"])} months</label>
            </fieldset>
            <fieldset class="cf-seg"><legend>Bridge shows</legend>
              <label><input type="radio" name="cf-metric" value="gross_profit" checked> Gross profit</label>
              <label><input type="radio" name="cf-metric" value="revenue"> Revenue</label>
            </fieldset>
          </div>
          <dl class="qf-stats cf-stats">
            <div><dt>Revenue</dt><dd class="num" id="cf-rev"></dd></div>
            <div><dt>Gross profit</dt><dd class="num" id="cf-gp"></dd></div>
            <div><dt>Gross margin</dt><dd class="num" id="cf-gm"></dd></div>
            <div><dt>Change in revenue</dt><dd class="num" id="cf-d-rev"></dd></div>
            <div><dt>Change in gross profit</dt><dd class="num" id="cf-d-gp"></dd></div>
            <div><dt>Change in margin</dt><dd class="num" id="cf-d-gm"></dd></div>
          </dl>
          <p class="mosca-summary" id="cf-summary" aria-live="polite"></p>
          <p class="cf-why">{WHY_SENTENCE}</p>
          <div class="cf-charts">
            <figure class="chart-wrap">
              <svg class="chart" id="cf-rev-chart" viewBox="0 0 640 300" width="640" height="300" role="img" aria-labelledby="cf-rev-t cf-rev-d"><title id="cf-rev-t">Monthly revenue, scenario against base plan</title><desc id="cf-rev-d"></desc></svg>
              <figcaption><span class="key cf-scen">Scenario</span><span class="key cf-base">Base plan</span><span class="key cf-band-key">Spread of scenario outcomes, P10 to P90</span></figcaption>
              <details><summary>Show the monthly numbers</summary><div class="table-scroll"><table class="mini cf-table" id="cf-month-table"><thead><tr><th scope="col">Month</th><th scope="col">Revenue</th><th scope="col">Gross profit</th><th scope="col">Margin</th><th scope="col">Spread P10 to P90</th><th scope="col">Base plan revenue</th></tr></thead><tbody></tbody></table></div></details>
            </figure>
            <figure class="chart-wrap">
              <svg class="chart" id="cf-bridge-chart" viewBox="0 0 640 300" width="640" height="300" role="img" aria-labelledby="cf-bridge-t cf-bridge-d"><title id="cf-bridge-t">Variance bridge from the base plan to the scenario</title><desc id="cf-bridge-d"></desc></svg>
              <figcaption><span class="key cf-bar-up">Adds</span><span class="key cf-bar-down">Takes away</span><span class="key cf-bar-total">Base plan and scenario</span></figcaption>
              <details><summary>Show the bridge numbers</summary><div class="table-scroll"><table class="mini cf-table" id="cf-bridge-table"><thead><tr><th scope="col">Step</th><th scope="col">Revenue</th><th scope="col">Gross profit</th><th scope="col">Gross margin</th></tr></thead><tbody></tbody></table></div></details>
            </figure>
          </div>
          <dl class="qf-stats cf-stats cf-stats-small">
            <div><dt>Spread of revenue outcomes</dt><dd class="num" id="cf-spread"></dd></div>
            <div><dt>Work deferred past the view</dt><dd class="num" id="cf-deferred"></dd></div>
          </dl>
          <p class="small">This is scenario analysis, not a forecast. The presets and sliders adjust around the real macro forecast, they do not predict it. The spread comes from redrawing weather, prices, rates and the macro forecast's past misses {model["monte_carlo"]["draws"]:,} times: a spread of scenario outcomes, not a probability. {e(model["extension_note"])}</p>
          <p><a class="btn" href="{wb["path"]}" download>Download the Excel model</a> <span class="small">Inputs, Drivers, Monthly Forecast and Bridge sheets, with live formulas and saved results, {wb["bytes"] // 1024} KB.</span></p>
          <noscript>{preset_table(con)}</noscript>
        </div>
{own_data_panel(d)}

        <div class="cf-how">
          <h3>How it works</h3>
          <details>
            <summary>What is real and what is fictional</summary>
            <p><strong>Real:</strong> the macro forecast of U.S. private nonresidential construction spending, its backtest, the O'Hare weather history, and the price and rate series, all public data pulled without API keys on {src["snapshot"]}. <strong>Fictional:</strong> {e(con["company"])}. Its backlog, bookings, margins and cost shares are synthetic, written for this demo, and every one is labeled in the engine's config as sourced or as an assumption.</p>
          </details>
          <details>
            <summary>The macro forecast and its backtest</summary>
            <p>The target is {e(macro["target"]["id"])}, in {e(macro["target"]["units"])}. {NUMBER_WORDS.get(len(lagged["table"]), len(lagged["table"]))} models were tested with a rolling-origin backtest: {lagged["backtest"]["origins"]} monthly forecast origins from {month(lagged["backtest"]["first_origin"][:7])} to {month(lagged["backtest"]["last_origin"][:7])}, each forecasting 1 to 12 months ahead. The rule for picking the published model was fixed before any backtest ran: lowest average MAPE over 1 to 12 months. It was run twice: lag 0 treats a month as known when it ends, lag 1 treats it as known a month later, which is about when Census publishes it. The published forecast uses lag {macro["published"]["publication_lag_months"]}.</p>
            {backtest_table(macro)}
            <p>{e(winner["name"])} wins under both. With lag {lagged["publication_lag_months"]} its average error is {lagged["winner_vs_seasonal_naive_pct"]:.1f}% lower than seasonal naive ({winner["mean_mape"]:.2f}% against {naive["mean_mape"]:.2f}%). The lagged drivers (employment, job openings, rates, metals, lumber and diesel) scored {drivers["mean_mape"]:.2f}%: they did not beat the simpler model, which is why the contractor layer is presented as scenarios and not as a forecast.</p>
            <figure class="chart-wrap">{macro_chart(macro)}
              <figcaption><span class="key cf-actual">Actual</span><span class="key cf-scen">Forecast</span><span class="key cf-band-key">P10 to P90 range of past misses</span></figcaption>
            </figure>
            <details><summary>Show the forecast numbers</summary>{forecast_table(macro)}</details>
            <p>The P10 to P90 band is read off the published model's backtest errors. It was also checked out of sample: rebuilt from earlier folds only, then tested on origins from {month(lagged["coverage"]["split"][:7])} on. A calibrated band would hold about 80%. It holds far less beyond the first few months, because spending surged in 2022 and 2023 and then stalled, and errors from the boom said little about the slowdown. Read it as the range of past misses, not an 80% probability.</p>
            {coverage_table(macro)}
          </details>
          <details>
            <summary>Data sources</summary>
            <p>All public, no API keys: FRED's CSV download and NOAA NCEI's data service. Every series ID was found by searching the FRED website, and the engine re-runs those searches to confirm them.</p>
            {sources_table(src)}
            <p>Weather: NOAA station {e(src["noaa"]["station"])}, {e(src["noaa"]["name"])}, {src["noaa"]["rows"]:,} daily records from {month(src["noaa"]["first"][:7])} to {month(src["noaa"]["last"][:7])}, pulled {src["noaa"]["pulled"]}. Architecture Billings Index: {e(src["abi"]).replace("skipped: no file at", "not included, because AIA does not publish it on FRED and no file was supplied at")}.</p>
          </details>
          <details>
            <summary>Weather thresholds and productivity</summary>
            {weather_table(src)}
            <p>A flagged weekday is a partly productive day, not a lost day. Each rule has a light and a severe tier, and a day takes the lowest factor among the rules it trips. Climatology covers {e(src["climatology_years"])}, because 2-minute wind records start in 1996. Work not done slips to later months, so a harsh winter moves revenue later rather than erasing it.</p>
            {factor_table(con["weather_tiers"], con["weather_factor_sources"]["by_factor"])}
          </details>
          <details>
            <summary>Scenario assumptions</summary>
            <p><strong>Tariffs</strong>, named by mechanism only. Each episode's size is the change in metal prices over its window, pushed through pass-through coefficients estimated from {model["materials"]["sample"][0]} to {model["materials"]["sample"][1]} monthly data (R squared {model["materials"]["r2"]}). Raised is 1 times the episode, reduced gives back half (an assumption), held is zero.</p>
            {episodes_list(model)}
            <p><strong>Rates.</strong> History cannot separate how rates affect construction from how the Fed responds to booms: every regression the engine ran says higher rates go with more construction growth later ({lo_h:+.3f} to {hi_h:+.3f} per 100 bp). So the scenario uses a labeled assumption: bookings fall {abs(100 * rates["bookings_per_100bp"]):.0f}% per +100 bp, after {rates["lag_months"]} months. The size comes from <a href="{e(con["rates_source"]["url"])}">{e(con["rates_source"]["title"])}</a>. {" ".join(e(c) for c in con["rates_caveats"])} The base path follows the Fed's {e(rates["projection_release"])} projections, from {rates["current"]["value"]}% in {month(rates["current"]["date"])} to {", ".join(f"{v}% at the end of {y}" for y, v in rates["projection"].items())}.</p>
            <p><strong>Public funding.</strong> A delayed surface transportation bill holds back {pct(model["funding"]["delayed_public_cut"], 0)} of public bookings for {model["funding"]["delay_months"]} months. An assumption.</p>
            <p><strong>Fuel.</strong> Diesel moves to the 10th or 90th percentile of its historical 12-month change ({100 * model["fuel"]["p10"]:+.1f}% or {100 * model["fuel"]["p90"]:+.1f}% in log terms) over the first year. Escalation clauses here cover materials, not fuel.</p>
            <p><strong>The company.</strong> Materials are {pct(model["costs"]["material_share"], 0)} of cost, escalation clauses pass {pct(model["costs"]["escalation_pass_through"], 0)} of a materials cost change to the owner, {pct(model["weather"]["exposure"], 0)} of work is weather-exposed, and new bookings start {model["bookings"]["start_delay_months"]} months after signing and run {model["bookings"]["duration_months"]} months. Base bookings are trailing bookings scaled by the macro forecast's growth. The synthetic backlog:</p>
            {backlog_table(model)}
          </details>
        </div>
        <p class="small provenance">Numbers from the forecasting engine at commit {e(prov["commit"])} ({prov["commit_date"]}), data snapshot {e(src["snapshot"])}. Source is private for now. Happy to walk through it in a call.</p>
        <!-- /gen:construction -->'''
    check_copy(html)
    return html


def verify_why(con: dict) -> None:
    """The panel says funding timing moves the 12-month revenue the most. Prove it from the presets."""
    main = str(con["model"]["main_months"])
    moves = {k: abs(r["change_from_base"][main]["revenue"]) for k, r in con["reference"].items() if k != "base"}
    if max(moves, key=moves.get) != "funding_delayed":
        raise SystemExit(f"the panel's sentence about funding timing is no longer true: {moves}")


def check_copy(html: str) -> None:
    text = unescape(re.sub(r"<[^>]+>", " ", html))            # what a reader sees, entities decoded
    for name, pattern in BANNED:
        hit = re.search(pattern, text)
        if hit:
            raise SystemExit(f"construction panel copy has a {name}: ...{text[max(0, hit.start() - 60):hit.end() + 20]}...")
