"""The generated parts of lab.html, and the data file the Mosca calculator reads.

Called by sitegen.py. Inputs are the two extractions in tools/data/, each written
by its own extractor from the source repo:

    pqc.json               tools/extract_pqc.py   -> assets/lab/pqc-data.js
    quantum_finance.json   tools/extract_qf.py    -> the <!-- gen:quantum --> region

The Monte Carlo chart is drawn here as static inline SVG, so it costs no script and
is readable without JavaScript. Its colours are theme variables.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

DATA = Path(__file__).resolve().parent / "data"


def load(name: str) -> dict:
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def pqc_js() -> str:
    d = load("pqc.json")
    keep = {k: d[k] for k in ("provenance", "as_of_year", "migration_years", "data_types", "scenarios")}
    return ("// Generated by tools/sitegen.py from tools/data/pqc.json (tools/extract_pqc.py).\n"
            "// Inputs from the Post-Quantum Readiness Toolkit's pqc_config.yaml. Do not edit.\n"
            "window.PQC_DATA = " + json.dumps(keep, indent=2, ensure_ascii=False) + ";\n")


def _n(v: int) -> str:
    return f"{v:,}"


# ------------------------------------------------------------ Monte Carlo chart -----
W, H = 480, 320
L, R, T, B = 78, 14, 14, 44
X0, X1 = 2.0, 4.6          # log10 of samples / queries
Y0, Y1 = -4.45, -1.7       # log10 of |error|, low enough for the slope -1 reference


def _px(n: float) -> float:
    return L + (math.log10(n) - X0) / (X1 - X0) * (W - L - R)


def _py(e: float) -> float:
    return T + (Y1 - math.log10(e)) / (Y1 - Y0) * (H - T - B)


def _path(points: list[tuple[float, float]]) -> str:
    return "M" + " L".join(f"{_px(n):.1f} {_py(e):.1f}" for n, e in points)


def mc_chart(mc: dict) -> str:
    c, q = mc["classical"], mc["quantum"]
    out = [f'<svg class="chart" viewBox="0 0 {W} {H}" width="{W}" height="{H}" role="img" '
           'aria-labelledby="mc-t mc-d">',
           '<title id="mc-t">Estimation error against cost, classical Monte Carlo and quantum '
           'amplitude estimation, log-log</title>',
           f'<desc id="mc-d">Classical Monte Carlo error falls from {c[0][1]} at {_n(c[0][0])} samples '
           f'to {c[-1][1]} at {_n(c[-1][0])} samples, about a slope of minus one half. Quantum '
           f'amplitude estimation error falls from {q[0][1]} at {_n(q[0][0])} queries to {q[-1][1]} '
           f'at {_n(q[-1][0])} queries, closer to a slope of minus one. The full numbers are in the '
           'table below the chart.</desc>']
    for k in range(2, 5):                                  # x grid: 100, 1,000, 10,000
        x = _px(10 ** k)
        out.append(f'<line class="ch-grid" x1="{x:.1f}" y1="{T}" x2="{x:.1f}" y2="{H - B}"/>')
        out.append(f'<text class="ch-tick" x="{x:.1f}" y="{H - B + 18}" text-anchor="middle">'
                   f'{_n(10 ** k)}</text>')
    for k in (-4, -3, -2):                                 # y grid: 0.0001, 0.001, 0.01
        y = _py(10 ** k)
        out.append(f'<line class="ch-grid" x1="{L}" y1="{y:.1f}" x2="{W - R}" y2="{y:.1f}"/>')
        out.append(f'<text class="ch-tick" x="{L - 8}" y="{y + 4:.1f}" text-anchor="end">'
                   f'{10 ** k:g}</text>')
    out.append(f'<text class="ch-axis" x="{(L + W - R) / 2}" y="{H - 6}" text-anchor="middle">'
               'Samples or oracle queries</text>')
    out.append(f'<text class="ch-axis" transform="translate(16 {(T + H - B) / 2}) rotate(-90)" '
               'text-anchor="middle">Error</text>')
    # Reference slopes from each series' first point, as the repo's chart draws them.
    n0, e0 = c[0]
    out.append(f'<path class="ch-ref ch-classical" d="{_path([(n0, e0), (c[-1][0], e0 * (c[-1][0] / n0) ** -0.5)])}"/>')
    m0, f0 = q[0]
    out.append(f'<path class="ch-ref ch-quantum" d="{_path([(m0, f0), (q[-1][0], f0 * (q[-1][0] / m0) ** -1)])}"/>')
    out.append(f'<path class="ch-line ch-classical" d="{_path(c)}"/>')
    out.append(f'<path class="ch-line ch-quantum" d="{_path(q)}"/>')
    out += [f'<circle class="ch-dot ch-classical" cx="{_px(n):.1f}" cy="{_py(e):.1f}" r="4"/>' for n, e in c]
    out += [f'<rect class="ch-dot ch-quantum" x="{_px(n) - 4:.1f}" y="{_py(e) - 4:.1f}" width="8" height="8"/>'
            for n, e in q]
    out.append("</svg>")
    return "".join(out)


def mc_table(mc: dict) -> str:
    rows = []
    for i, (n, e) in enumerate(mc["classical"]):
        qn, qe = mc["quantum"][i] if i < len(mc["quantum"]) else ("", "")
        rows.append(f"<tr><td class=\"num\">{_n(n)}</td><td class=\"num\">{e}</td>"
                    f"<td class=\"num\">{_n(qn) if qn != '' else ''}</td><td class=\"num\">{qe}</td></tr>")
    return ('<table class="mini"><thead><tr><th scope="col">Samples</th><th scope="col">Classical error</th>'
            '<th scope="col">Queries</th><th scope="col">Quantum error</th></tr></thead><tbody>'
            + "".join(rows) + "</tbody></table>")


def quantum_region() -> str:
    d = load("quantum_finance.json")
    pf, mc, fc = d["portfolio"], d["monte_carlo"], d["forecaster"]
    same = pf["classical"]["holdings"] == pf["quantum"]["holdings"]
    if pf["matched"] != same:
        raise SystemExit("portfolio verdict disagrees with the holdings it printed")
    fc_rows = "".join(
        f'<tr><th scope="row">Month {f["month"]}</th><td class="num">${_n(f["classical"])}</td>'
        f'<td class="num">${_n(f["quantum"])}</td></tr>' for f in fc["forecast"])
    last = fc["last_actual"]
    return f'''<!-- gen:quantum -->
        <div class="qf-grid">
          <article class="qf-card" aria-labelledby="qaoa-h">
            <h3 id="qaoa-h">QAOA portfolio</h3>
            <p class="verdict"><span class="pill ok">{"Matched brute force" if pf["matched"] else "Did not match"}</span></p>
            <p>Pick exactly {pf["held"]} of {pf["stocks"]} stocks for low risk at a {pf["target"]} return target. QAOA chose the same {pf["held"]} stocks as an exhaustive classical search.</p>
            <dl class="qf-stats">
              <div><dt>Brute force checked</dt><dd class="num">{_n(pf["classical"]["evaluated"])}</dd></div>
              <div><dt>QAOA measured</dt><dd class="num">{_n(pf["quantum"]["evaluated"])}</dd></div>
              <div><dt>Circuit runs to tune angles</dt><dd class="num">{_n(pf["circuit_evaluations"])}</dd></div>
              <div><dt>Expected return</dt><dd class="num">{pf["quantum"]["return"]}</dd></div>
              <div><dt>Risk, annual std dev</dt><dd class="num">{pf["quantum"]["risk"]}</dd></div>
            </dl>
            <p class="small">At {pf["stocks"]} stocks brute force still wins easily. The case for QAOA is at 100 or more stocks, where checking every portfolio becomes impossible.</p>
          </article>

          <article class="qf-card" aria-labelledby="fc-h">
            <h3 id="fc-h">Revenue forecaster</h3>
            <p class="verdict"><span class="pill loss">Honest loss: classical won</span></p>
            <p>Forecast three months past {last["month"]} months of rising revenue (month {last["month"]}: <span class="num">${_n(last["revenue"])}</span>).</p>
            <table class="mini"><thead><tr><th scope="col"><span class="sr-only">Month</span></th><th scope="col">Linear regression</th><th scope="col">1-qubit VQR</th></tr></thead><tbody>{fc_rows}</tbody></table>
            <p class="small">Linear regression extends the trend. A one-qubit, angle-encoded model interpolates inside the range it saw and cannot extrapolate a straight trend, so its forecast flattens. Kept on the site on purpose.</p>
          </article>

          <article class="qf-card qf-wide" aria-labelledby="mc-h">
            <h3 id="mc-h">Monte Carlo risk: the quadratic speedup</h3>
            <p>The probability a small business runs low on cash during the year, estimated two ways. Classical error falls like 1/&radic;N, amplitude estimation error like 1/M, so halving the error costs 4x the samples but only 2x the queries.</p>
            <figure class="chart-wrap">
              {mc_chart(mc)}
              <figcaption><span class="key ch-classical">Classical Monte Carlo</span><span class="key ch-quantum">Quantum amplitude estimation</span><span class="key ch-ref-key">Reference slopes</span></figcaption>
            </figure>
            <p>To reach {mc["target_accuracy"]} error: <span class="num">{_n(mc["classical_to_target"])}</span> classical samples, <span class="num">{_n(mc["quantum_to_target"])}</span> quantum oracle queries. The reference probability is <span class="num">{mc["reference_p"]}</span>, from <span class="num">{_n(mc["reference_sims"])}</span> classical simulations.</p>
            <p class="small">The honest caveat: the quantum side uses a one-qubit oracle calibrated to the same probability, because loading the full cash-flow model into a circuit is the hard, open part. On a laptop simulator, classical still finishes first in wall-clock time. The advantage shown is in query counts.</p>
            <details><summary>Show the numbers</summary>{mc_table(mc)}</details>
          </article>
        </div>
        <p class="small provenance">Numbers are the printed output of the repo's own seeded scripts, run as committed at {d["commit"][:7]} (Python {d["python"]}, Qiskit {d["qiskit"]}). The repo commits its charts, not its numbers.</p>
        <p><a class="btn" href="{d["repo"]}">Read the code on GitHub</a></p>
        <!-- /gen:quantum -->'''
